\connect mood_api_db

INSERT INTO public.mood_type (name, description) VALUES
('Happy', 'Feeling joyful, content, and positive about the day'),
('Sad', 'Feeling down, melancholic, or experiencing a sense of loss'),
('Anxious', 'Feeling worried, nervous, or uneasy about present or future events'),
('Calm', 'Feeling peaceful, relaxed, and in a state of tranquility'),
('Energetic', 'Feeling full of energy, motivated, and ready to take on challenges'),
('Tired', 'Feeling exhausted, drained, or lacking physical or mental energy'),
('Angry', 'Feeling frustrated, irritated, or experiencing strong displeasure'),
('Grateful', 'Feeling thankful and appreciative of people or circumstances'),
('Stressed', 'Feeling overwhelmed by pressures, demands, or responsibilities'),
('Neutral', 'Feeling balanced with no strong emotions, just going through the day');

INSERT INTO public.advice_type (name, description) VALUES
('Motivation', 'Inspirational content to boost energy and drive'),
('Self-Care', 'Tips for taking care of your physical and mental well-being'),
('Mindfulness', 'Practices for being present and aware'),
('Productivity', 'Strategies to get things done efficiently'),
('Relaxation', 'Techniques to unwind and reduce tension'),
('Social Connection', 'Ideas for connecting with others'),
('Exercise', 'Physical activity suggestions'),
('Gratitude', 'Practices for appreciation and thankfulness'),
('Problem Solving', 'Approaches to tackle challenges'),
('Breathing Exercises', 'Techniques to calm the mind and body');

INSERT INTO public.mood_advice_type_mapping (mood_type_id, advice_type_id, priority) VALUES
-- Happy (id=1)
(1, 4, 1),  -- Happy -> Productivity
(1, 7, 2),  -- Happy -> Exercise
(1, 6, 3),  -- Happy -> Social Connection
(1, 8, 4),  -- Happy -> Gratitude

-- Sad (id=2)
(2, 2, 1),  -- Sad -> Self-Care
(2, 1, 2),  -- Sad -> Motivation
(2, 6, 3),  -- Sad -> Social Connection
(2, 8, 4),  -- Sad -> Gratitude

-- Anxious (id=3)
(3, 10, 1), -- Anxious -> Breathing Exercises
(3, 3, 2),  -- Anxious -> Mindfulness
(3, 5, 3),  -- Anxious -> Relaxation
(3, 9, 4),  -- Anxious -> Problem Solving

-- Calm (id=4)
(4, 3, 1),  -- Calm -> Mindfulness
(4, 8, 2),  -- Calm -> Gratitude
(4, 4, 3),  -- Calm -> Productivity
(4, 5, 4),  -- Calm -> Relaxation

-- Energetic (id=5)
(5, 7, 1),  -- Energetic -> Exercise
(5, 4, 2),  -- Energetic -> Productivity
(5, 6, 3),  -- Energetic -> Social Connection
(5, 1, 4),  -- Energetic -> Motivation

-- Tired (id=6)
(6, 5, 1),  -- Tired -> Relaxation
(6, 2, 2),  -- Tired -> Self-Care
(6, 3, 3),  -- Tired -> Mindfulness
(6, 10, 4), -- Tired -> Breathing Exercises

-- Angry (id=7)
(7, 10, 1), -- Angry -> Breathing Exercises
(7, 7, 2),  -- Angry -> Exercise
(7, 5, 3),  -- Angry -> Relaxation
(7, 9, 4),  -- Angry -> Problem Solving

-- Grateful (id=8)
(8, 8, 1),  -- Grateful -> Gratitude
(8, 6, 2),  -- Grateful -> Social Connection
(8, 3, 3),  -- Grateful -> Mindfulness
(8, 1, 4),  -- Grateful -> Motivation

-- Stressed (id=9)
(9, 10, 1), -- Stressed -> Breathing Exercises
(9, 5, 2),  -- Stressed -> Relaxation
(9, 9, 3),  -- Stressed -> Problem Solving
(9, 2, 4),  -- Stressed -> Self-Care

-- Neutral (id=10)
(10, 3, 1), -- Neutral -> Mindfulness
(10, 4, 2), -- Neutral -> Productivity
(10, 8, 3), -- Neutral -> Gratitude
(10, 7, 4); -- Neutral -> Exercise

-- Motivation advice (50 records)
INSERT INTO public.advice (advice_type_id, title, content) VALUES
(1, 'Start your day with a clear goal', 'Identify one main goal for today and focus on achieving it. This gives you direction and purpose.'),
(1, 'Break big tasks into smaller steps', 'Large projects feel overwhelming. Divide them into manageable chunks and celebrate each completion.'),
(1, 'Remember your past successes', 'Think back to a time you overcame a challenge. You have the strength to do it again.'),
(1, 'Visualize your success', 'Spend 5 minutes imagining yourself successfully completing your goal. This builds confidence.'),
(1, 'Find your why', 'Connect with the deeper reason behind your goal. This makes motivation more meaningful.'),
(1, 'Create a progress tracker', 'Visually track your progress. Seeing advancement is incredibly motivating.'),
(1, 'Read an inspirational quote', 'Find a quote that resonates with you and repeat it throughout the day.'),
(1, 'Take action immediately', 'Don''t wait for the perfect moment. Start now, even with small steps.'),
(1, 'Reward yourself for progress', 'Set up small rewards for completing milestones. Positive reinforcement works.'),
(1, 'Find an accountability partner', 'Share your goals with someone who will check in on your progress.'),
(1, 'Listen to motivational music', 'Create a playlist of energizing songs to boost your mood and drive.'),
(1, 'Learn from setbacks', 'Every failure is a lesson. What can you learn from this experience?'),
(1, 'Focus on progress, not perfection', 'You don''t need to be perfect. Small improvements over time lead to big results.'),
(1, 'Celebrate small wins', 'Don''t wait for the final goal. Acknowledge and celebrate progress along the way.'),
(1, 'Change your environment', 'Sometimes a new location or fresh air can reignite your motivation.'),
(1, 'Read a success story', 'Learn how others overcame similar challenges. You''re not alone.'),
(1, 'Set a deadline', 'Deadlines create urgency and can help you stay focused and motivated.'),
(1, 'Do something you''re good at', 'Remind yourself of your strengths by doing something you excel at.'),
(1, 'Connect with your purpose', 'How does this goal align with your values and life purpose?'),
(1, 'Take care of your basics', 'Eat well, sleep enough, and exercise. A healthy body fuels motivation.'),
(1, 'Find inspiration in nature', 'Take a walk outside. Nature has a way of renewing motivation.'),
(1, 'Commit to one small action', 'You don''t need to do everything today. Just commit to one meaningful action.'),
(1, 'Ask for help', 'Getting support from others can reignite your motivation and make tasks easier.'),
(1, 'Review your values', 'Reconnect with what matters most to you. Let this guide your motivation.'),
(1, 'Practice positive self-talk', 'Replace doubt with encouragement. Talk to yourself like you''d talk to a good friend.'),
(1, 'Watch a TED talk', 'Listening to inspiring talks can spark new ideas and motivation.'),
(1, 'Create a vision board', 'Visualize your goals with images and words. Look at it daily for inspiration.'),
(1, 'Join a community', 'Surround yourself with people working toward similar goals.'),
(1, 'Track your energy levels', 'Work on important tasks when you have the most energy.'),
(1, 'Reframe your challenges', 'Instead of "I have to", try "I get to". This shifts your mindset.'),
(1, 'Read about others'' journeys', 'Learning about others'' paths to success can inspire your own.'),
(1, 'Set a timer for focused work', 'Use the Pomodoro technique to work in focused 25-minute bursts.'),
(1, 'Clarify your why statement', 'Write down why this goal matters to you. Keep it somewhere visible.'),
(1, 'Find a role model', 'Who inspires you? How would they approach this challenge?'),
(1, 'Do a personal inventory', 'List your skills and accomplishments. Remember you''re capable.'),
(1, 'Plan your week', 'Having a clear weekly plan gives you direction and reduces overwhelm.'),
(1, 'Practice gratitude for progress', 'Be thankful for how far you''ve come, not just where you''re going.'),
(1, 'Remove distractions', 'Turn off notifications and create a focused work environment.'),
(1, 'Start with the hardest task', 'Tackle your biggest challenge when your energy is highest.'),
(1, 'Write down your goals', 'The act of writing makes goals feel more real and achievable.'),
(1, 'Embrace the learning process', 'Every step forward is progress, even if it doesn''t feel like it.'),
(1, 'Find quick wins', 'Complete small, easy tasks to build momentum.'),
(1, 'Practice self-compassion', 'Be kind to yourself when things get difficult.'),
(1, 'Review what''s working', 'What strategies have helped you before? Use them again.'),
(1, 'Imagine the outcome', 'What will you feel when you accomplish this goal?'),
(1, 'Take a cold shower', 'A quick jolt of cold water can energize you and boost motivation.'),
(1, 'Do something kind', 'Helping others often reignites our sense of purpose and motivation.');

-- Self-Care advice (50 records)
INSERT INTO public.advice (advice_type_id, title, content) VALUES
(2, 'Take a warm bath', 'Soak in warm water to relax your muscles and calm your mind.'),
(2, 'Get enough sleep', 'Aim for 7-9 hours of quality sleep. Rest is the foundation of self-care.'),
(2, 'Moisturize your skin', 'Apply lotion or oil to nourish your skin. This simple act feels nurturing.'),
(2, 'Drink more water', 'Hydration improves mood and energy. Drink a glass of water right now.'),
(2, 'Take a digital break', 'Step away from screens for at least an hour. Your eyes and mind need rest.'),
(2, 'Wear comfortable clothes', 'Dress in something that makes you feel good and comfortable.'),
(2, 'Stretch your body', 'Gentle stretching releases tension and increases circulation.'),
(2, 'Prepare a healthy meal', 'Cook something nutritious that you enjoy eating.'),
(2, 'Take a relaxing bath with essential oils', 'Add lavender or eucalyptus oil for extra relaxation.'),
(2, 'Do a face mask', 'Use a moisturizing or soothing face mask for 15-20 minutes.'),
(2, 'Get a manicure or pedicure', 'Pamper yourself with some hand and foot care.'),
(2, 'Trim your nails', 'Keep your nails clean and neat for a fresh feeling.'),
(2, 'Floss your teeth', 'Take care of your dental health as part of self-care.'),
(2, 'Do your skincare routine', 'Follow a consistent routine that makes you feel cared for.'),
(2, 'Take a nature walk', 'Spend time outdoors in fresh air. This is powerful self-care.'),
(2, 'Journal your feelings', 'Write down what''s on your mind. This helps process emotions.'),
(2, 'Eat a healthy snack', 'Choose fruits, nuts, or yogurt for a nutritious boost.'),
(2, 'Take a long shower', 'Let hot water wash away tension from your body.'),
(2, 'Listen to calming music', 'Choose soothing instrumental or nature sounds.'),
(2, 'Practice deep breathing', 'Slow, deep breaths calm your nervous system.'),
(2, 'Dim the lights', 'Create a cozy atmosphere with softer lighting.'),
(2, 'Light a candle', 'Use a scented candle to create a calming environment.'),
(2, 'Make a cup of tea', 'Brew a warm, comforting cup of herbal tea.'),
(2, 'Read a book', 'Get lost in a good story for relaxation and escape.'),
(2, 'Do a gentle yoga session', 'Practice slow, mindful yoga for physical and mental wellness.'),
(2, 'Take a power nap', 'Rest for 20-30 minutes to recharge your energy.'),
(2, 'Create a bedtime routine', 'Establish calming habits before sleep.'),
(2, 'Unclutter a small space', 'Organize one drawer or shelf. A tidy space feels peaceful.'),
(2, 'Eat something you love', 'Enjoy a favorite treat mindfully and without guilt.'),
(2, 'Get a haircut', 'A fresh hairstyle can make you feel renewed.'),
(2, 'Wear your favorite outfit', 'Choose clothes that make you feel confident and comfortable.'),
(2, 'Schedule time for rest', 'Block off time in your calendar dedicated to relaxation.'),
(2, 'Take vitamins if needed', 'Ensure you''re getting necessary nutrients for health.'),
(2, 'Do a guided meditation', 'Follow a meditation app or video for 10-20 minutes.'),
(2, 'Take a leisurely walk', 'Walk without a destination, just for the joy of it.'),
(2, 'Write a gratitude list', 'List things you''re grateful for in your life right now.'),
(2, 'Spend time with a pet', 'Cuddle or play with a pet for comfort and connection.'),
(2, 'Call a loved one', 'Connect with someone who makes you feel cared for.'),
(2, 'Limit caffeine', 'Reduce stress by cutting back on caffeine intake.'),
(2, 'Stretch before bed', 'Gentle stretching helps you sleep better.'),
(2, 'Wear cozy socks', 'Sometimes comfort is found in the simplest things.'),
(2, 'Take a day off', 'Give yourself permission to rest without guilt.'),
(2, 'Practice saying no', 'Protect your energy by declining non-essential commitments.'),
(2, 'Pamper your hands', 'Give yourself a hand massage or moisturize thoroughly.'),
(2, 'Create a cozy corner', 'Designate a comfortable space for relaxation.'),
(2, 'Express your creativity', 'Draw, paint, or craft without worrying about the result.');

-- Mindfulness advice (50 records)
INSERT INTO public.advice (advice_type_id, title, content) VALUES
(3, 'Practice present moment awareness', 'Focus on what''s happening right now, not past or future worries.'),
(3, 'Notice five things around you', 'Observe 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste.'),
(3, 'Eat mindfully', 'Without distractions, notice the flavors, textures, and sensations of your food.'),
(3, 'Practice body scanning', 'Mentally scan from head to toe, noticing sensations without judgment.'),
(3, 'Watch your thoughts pass by', 'Imagine thoughts as clouds passing through the sky. Observe them without attaching to them.'),
(3, 'Focus on your breath', 'Count your breaths: in for 4, hold for 4, out for 4.'),
(3, 'Meditate for 5 minutes', 'Sit quietly and observe your thoughts without reaction.'),
(3, 'Mindfully wash dishes', 'Pay attention to water temperature, textures, and scents.'),
(3, 'Listen fully in conversations', 'Give someone your complete attention without planning your response.'),
(3, 'Take a mindful walk', 'Notice every step, the feeling of your feet, your surroundings.'),
(3, 'Practice single-tasking', 'Do one thing at a time with full attention.'),
(3, 'Observe your emotions', 'Notice emotions without judging yourself for having them.'),
(3, 'Practice loving-kindness meditation', 'Send positive thoughts to yourself and others.'),
(3, 'Mindfully brush your teeth', 'Feel the sensations of brushing without rushing.'),
(3, 'Notice your five senses', 'Take turns focusing on each sense one at a time.'),
(3, 'Practice acceptance', 'Accept what is happening right now without resistance.'),
(3, 'Meditate on gratitude', 'Think about things you''re grateful for during meditation.'),
(3, 'Be present with loved ones', 'Put away your phone and be fully present when with people you care about.'),
(3, 'Practice mindful listening', 'Listen with your whole being, not just your ears.'),
(3, 'Notice small joys', 'Appreciate small moments: a good cup of coffee, a smile, warm sunshine.'),
(3, 'Do a body awareness meditation', 'Focus on the weight of your body and your connection to the earth.'),
(3, 'Practice non-judgment', 'Observe thoughts and feelings without labeling them as good or bad.'),
(3, 'Mindfully stretch', 'Stretch slowly, noticing every sensation and limitation.'),
(3, 'Practice breathing exercises', 'Try box breathing: inhale, hold, exhale, hold equally.'),
(3, 'Observe nature mindfully', 'Watch clouds, water, trees, or animals with full attention.'),
(3, 'Practice mindful journaling', 'Write slowly and intentionally about your day.'),
(3, 'Do a loving-kindness practice', 'Consciously send love and compassion to yourself and others.'),
(3, 'Practice mindful eating meditation', 'Take a piece of food and experience it with all your senses.'),
(3, 'Notice your automatic thoughts', 'Become aware of repetitive thoughts without getting caught in them.'),
(3, 'Practice gratitude meditation', 'Sit and meditate while thinking about what you''re grateful for.'),
(3, 'Be aware of your reactions', 'Notice how you react to situations and practice pausing before responding.'),
(3, 'Mindfully do routine tasks', 'Bring full awareness to brushing teeth, showering, or cooking.'),
(3, 'Practice self-compassion meditation', 'Focus on kindness toward yourself during difficult moments.'),
(3, 'Notice your breath throughout the day', 'Set reminders to pause and take a few conscious breaths.'),
(3, 'Observe without trying to fix', 'Practice being present with difficulties without immediately trying to solve them.'),
(3, 'Practice loving your body', 'Focus on appreciation for your body and what it does for you.'),
(3, 'Mindfully prepare a meal', 'Prepare food with intention, noticing every ingredient and process.'),
(3, 'Practice gratitude for sensations', 'Appreciate the feel of warmth, coolness, textures against your skin.'),
(3, 'Do a visual meditation', 'Focus on a peaceful image and explore it mentally.'),
(3, 'Practice mindful communication', 'Speak slowly and thoughtfully, listening carefully to others.'),
(3, 'Notice patterns in your thoughts', 'Observe recurring thoughts without judgment.'),
(3, 'Practice being with discomfort', 'Sit with difficult feelings, observing them curiously.'),
(3, 'Mindfully enjoy a favorite activity', 'Do something you love with complete attention.'),
(3, 'Practice present-moment awareness', 'Throughout the day, pause and notice what you''re experiencing now.'),
(3, 'Do a body-based meditation', 'Focus awareness on physical sensations throughout your body.'),
(3, 'Practice acceptance meditation', 'Accept difficult thoughts and feelings as they arise.');

-- Productivity advice (50 records)
INSERT INTO public.advice (advice_type_id, title, content) VALUES
(4, 'Make a to-do list', 'Write down your tasks for today. Seeing them listed is motivating.'),
(4, 'Prioritize your top three tasks', 'Focus on the three most important things. Everything else is secondary.'),
(4, 'Use the Pomodoro Technique', 'Work for 25 minutes, then take a 5-minute break. Repeat four times, then take a longer break.'),
(4, 'Eliminate distractions', 'Turn off notifications, close unnecessary tabs, and create a focused work environment.'),
(4, 'Start with the hardest task', 'Tackle your biggest challenge when your energy is peak.'),
(4, 'Time block your day', 'Assign specific time slots for different types of tasks.'),
(4, 'Use a timer', 'Visual representation of time helps you stay focused.'),
(4, 'Batch similar tasks', 'Group similar activities together for efficiency.'),
(4, 'Take regular breaks', 'Short breaks prevent burnout and maintain focus.'),
(4, 'Plan your day the night before', 'Write your to-do list before bed to start strong.'),
(4, 'Set realistic goals', 'Aim for what''s achievable, not what''s overwhelming.'),
(4, 'Use the two-minute rule', 'If a task takes less than two minutes, do it immediately.'),
(4, 'Create a shutdown ritual', 'End your workday with a consistent routine that signals completion.'),
(4, 'Keep a notepad nearby', 'Capture ideas quickly so they don''t distract you.'),
(4, 'Delete low-priority tasks', 'It''s okay to remove things that don''t matter.'),
(4, 'Use productivity apps', 'Try Todoist, Asana, or other tools that work for your style.'),
(4, 'Set clear deadlines', 'Deadlines create urgency and keep you moving.'),
(4, 'Break projects into milestones', 'Large projects feel manageable when divided into smaller goals.'),
(4, 'Work during your peak hours', 'Identify when you''re most alert and do important work then.'),
(4, 'Say no to non-essentials', 'Protect your time by declining commitments that don''t align with priorities.'),
(4, 'Create an ideal work environment', 'Good lighting, comfortable chair, and organized space boost productivity.'),
(4, 'Use a calendar for scheduling', 'Block off time for different activities to avoid surprises.'),
(4, 'Automate repetitive tasks', 'Use tools or scripts to handle routine work automatically.'),
(4, 'Review your to-do list regularly', 'Update priorities and remove completed tasks.'),
(4, 'Practice single-tasking', 'Multitasking reduces efficiency. Focus on one thing at a time.'),
(4, 'Set a specific end time', 'Know when your workday ends to maintain work-life balance.'),
(4, 'Reward completed tasks', 'Celebrate finishing tasks with a small reward.'),
(4, 'Keep your workspace clean', 'A tidy environment supports focused work.'),
(4, 'Use the Eisenhower Matrix', 'Categorize tasks by importance and urgency.'),
(4, 'Take notes during meetings', 'Writing keeps you engaged and creates actionable items.'),
(4, 'Communicate deadlines clearly', 'Set expectations with others to avoid confusion.'),
(4, 'Use email templates', 'Respond faster to common messages with prepared templates.'),
(4, 'Batch your email checking', 'Check email at set times, not constantly.'),
(4, 'Create a project checklist', 'Know exactly what needs to be done to complete a project.'),
(4, 'Use a kanban board', 'Visualize your workflow with columns like To Do, Doing, Done.'),
(4, 'Delegate when possible', 'Free up your time for high-priority work.'),
(4, 'Set a timer for meetings', 'Keep meetings focused and on schedule.'),
(4, 'Use keyboard shortcuts', 'Speed up repetitive actions on your computer.'),
(4, 'Take a micro-break for mental clarity', 'A 2-minute walk can improve focus.'),
(4, 'Eat nutritious meals', 'Good nutrition supports sustained energy and focus.'),
(4, 'Practice saying "later, not now"', 'Defer less important tasks to protect your focus.'),
(4, 'Simplify your process', 'Look for unnecessary steps you can eliminate.'),
(4, 'Use a mind map for planning', 'Visualize project scope and connections.'),
(4, 'Block a focus hour', 'Reserve one hour daily for your most important work.'),
(4, 'Review your week on Friday', 'Assess what worked and what needs adjustment.'),
(4, 'Use project management tools', 'Tools like Monday.com or Asana organize team work.'),
(4, 'Practice continuous improvement', 'Reflect regularly on how to work more efficiently.');

-- Relaxation advice (50 records)
INSERT INTO public.advice (advice_type_id, title, content) VALUES
(5, 'Try progressive muscle relaxation', 'Tense and release each muscle group for 5 seconds.'),
(5, 'Take a long, slow shower', 'Let warm water relax your body and mind.'),
(5, 'Lie down on your back', 'Place a pillow under your knees for comfort and relaxation.'),
(5, 'Listen to ambient sounds', 'Try rain, ocean waves, or forest sounds.'),
(5, 'Drink herbal tea', 'Chamomile or lavender tea promotes relaxation.'),
(5, 'Practice slow, deep breathing', 'Breathe in through your nose, out through your mouth.'),
(5, 'Use a heating pad', 'Warmth on sore muscles promotes relaxation.'),
(5, 'Dim the lights', 'Soft lighting creates a calming atmosphere.'),
(5, 'Stretch gently', 'Hold stretches for 30 seconds each for relaxation.'),
(5, 'Close your eyes', 'Give your eyes and mind a rest from stimulation.'),
(5, 'Use a diffuser with essential oils', 'Lavender, eucalyptus, or chamomile oils promote relaxation.'),
(5, 'Wear loose clothing', 'Tight clothes can restrict and create tension.'),
(5, 'Sit in silence', 'Spend 10 minutes without any noise or distractions.'),
(5, 'Do gentle yoga', 'Slow yoga movements help release tension.'),
(5, 'Listen to calming music', 'Classical or ambient music reduces stress.'),
(5, 'Take a warm bath with Epsom salt', 'Epsom salt can soothe muscles and promote relaxation.'),
(5, 'Practice autogenic relaxation', 'Repeat calming phrases like "I am calm and relaxed."'),
(5, 'Massage your temples', 'Gentle massage can relieve tension headaches.'),
(5, 'Visualize a peaceful place', 'Picture yourself in a calm, safe environment.'),
(5, 'Do a body scan meditation', 'Notice and release tension in each body part.'),
(5, 'Avoid caffeine', 'Cut off caffeine 6+ hours before bedtime.'),
(5, 'Create a cozy space', 'Make a comfortable area with blankets and pillows.'),
(5, 'Use a white noise machine', 'White noise can block stressful sounds.'),
(5, 'Do restorative yoga', 'Hold poses for longer periods for deep relaxation.'),
(5, 'Practice tension release', 'Squeeze muscles briefly then relax to release tension.'),
(5, 'Sit outside in nature', 'Fresh air and natural surroundings are deeply relaxing.'),
(5, 'Take a nap', 'A 20-30 minute nap can significantly reduce stress.'),
(5, 'Read something light', 'Light reading distracts from stress.'),
(5, 'Do an eye relaxation exercise', 'Close eyes and massage the area around them.'),
(5, 'Use a neck pillow', 'Proper neck support prevents tension.'),
(5, 'Practice box breathing', 'Inhale 4, hold 4, exhale 4, hold 4.'),
(5, 'Get a professional massage', 'Professional touch releases deep tension.'),
(5, 'Use a foot massager', 'Massage your feet for instant relaxation.'),
(5, 'Watch something soothing', 'Nature documentaries or gentle shows promote relaxation.'),
(5, 'Light a scented candle', 'Calming scents enhance relaxation.'),
(5, 'Do jaw relaxation', 'Release clenching by slowly moving your jaw.'),
(5, 'Wear a weighted blanket', 'Gentle pressure promotes relaxation and sleep.'),
(5, 'Practice shoulder rolls', 'Roll shoulders backward slowly to release tension.'),
(5, 'Use an eye mask', 'Block out light for better relaxation.'),
(5, 'Avoid screens before bed', 'Blue light interferes with relaxation.'),
(5, 'Do hand relaxation', 'Stretch and massage your hands gently.'),
(5, 'Try a steam room or sauna', 'Heat promotes muscle relaxation and stress relief.'),
(5, 'Practice gentle neck stretches', 'Slowly stretch your neck in all directions.'),
(5, 'Use a humidifier', 'Moisture in the air can promote relaxation.'),
(5, 'Listen to a guided relaxation', 'Follow a recording that walks you through relaxation.');

-- Social Connection advice (50 records)
INSERT INTO public.advice (advice_type_id, title, content) VALUES
(6, 'Call a friend', 'Hearing a familiar voice is instantly comforting.'),
(6, 'Send a text to someone you care about', 'A simple message can brighten someone''s day and yours.'),
(6, 'Plan a video call', 'Face-to-face connection, even virtual, strengthens bonds.'),
(6, 'Invite someone for coffee', 'In-person time is valuable for connection.'),
(6, 'Join a group or club', 'Find people who share your interests.'),
(6, 'Volunteer', 'Helping others creates meaningful connections.'),
(6, 'Attend a community event', 'Being around others fosters connection.'),
(6, 'Write a letter to someone', 'Handwritten notes show genuine care.'),
(6, 'Have a meal with loved ones', 'Sharing food strengthens relationships.'),
(6, 'Initiate plans', 'Don''t wait for others; take the first step.'),
(6, 'Listen actively to someone', 'Give someone your full attention and interest.'),
(6, 'Share your feelings with someone you trust', 'Vulnerability deepens connections.'),
(6, 'Compliment someone genuinely', 'Make someone feel valued and seen.'),
(6, 'Attend a social gathering', 'Put yourself in environments where you can meet people.'),
(6, 'Create a group chat with friends', 'Regular communication keeps connections strong.'),
(6, 'Organize a game night', 'Fun shared activities strengthen bonds.'),
(6, 'Ask someone for advice', 'People enjoy being asked for their perspective.'),
(6, 'Send a funny meme to a friend', 'Laughter shared is connection strengthened.'),
(6, 'Attend a class or workshop', 'Shared learning creates connections.'),
(6, 'Visit a family member', 'Family connection is deeply nourishing.'),
(6, 'Join an online community', 'Connect with people who share your interests.'),
(6, 'Participate in a book club', 'Discussing ideas with others fosters connection.'),
(6, 'Be present without distractions', 'Put away your phone when spending time with others.'),
(6, 'Ask meaningful questions', 'Go deeper with conversations beyond small talk.'),
(6, 'Show gratitude to someone', 'Tell someone how they''ve positively impacted you.'),
(6, 'Attend a workshop or seminar', 'Learning with others creates connections.'),
(6, 'Start a hobby group', 'Gather with others who enjoy what you enjoy.'),
(6, 'Have a heart-to-heart conversation', 'Share deeper thoughts with someone close.'),
(6, 'Support a friend through a challenge', 'Being there for others strengthens bonds.'),
(6, 'Attend a networking event', 'Professional connections are also valuable.'),
(6, 'Cook for someone', 'Sharing food you''ve prepared shows care.'),
(6, 'Help someone move or with a project', 'Practical support deepens connection.'),
(6, 'Remember important dates', 'Birthdays and anniversaries show you care.'),
(6, 'Have a spontaneous hangout', 'Unplanned time together can be special.'),
(6, 'Share your passions with others', 'When you talk about what excites you, others connect with that energy.'),
(6, 'Be vulnerable', 'Sharing struggles invites others to do the same.'),
(6, 'Celebrate someone''s success', 'Genuine excitement for others'' wins strengthens bonds.'),
(6, 'Join a fitness class', 'Group exercise creates accountability and connection.'),
(6, 'Attend a concert or event with others', 'Shared experiences create lasting memories.'),
(6, 'Have a regular meetup', 'Consistency in connection matters.'),
(6, 'Send an encouraging message', 'Let someone know you believe in them.'),
(6, 'Be interested in others'' lives', 'Genuine curiosity strengthens relationships.'),
(6, 'Make eye contact', 'It signals attention and genuine connection.'),
(6, 'Apologize if you''ve hurt someone', 'Repair strengthens relationships.'),
(6, 'Share a meal delivery with someone', 'Acts of kindness deepen connection.'),
(6, 'Play a sport together', 'Shared physical activity bonds people.');

-- Exercise advice (50 records)
INSERT INTO public.advice (advice_type_id, title, content) VALUES
(7, 'Take a 30-minute walk', 'Simple walking boosts mood and fitness.'),
(7, 'Do 10 push-ups', 'Even a small strength session counts.'),
(7, 'Stretch for 10 minutes', 'Stretching improves flexibility and reduces tension.'),
(7, 'Do a short yoga session', 'Yoga combines strength, flexibility, and calm.'),
(7, 'Run or jog', 'Cardio boosts endorphins significantly.'),
(7, 'Do jumping jacks', 'A quick cardio burst increases heart rate.'),
(7, 'Go for a bike ride', 'Cycling is excellent low-impact exercise.'),
(7, 'Do planks', 'Planks strengthen your core effectively.'),
(7, 'Dance', 'Dancing is exercise that''s also fun.'),
(7, 'Try swimming', 'Swimming works all muscle groups.'),
(7, 'Do squats', 'Squats build leg strength and endurance.'),
(7, 'Walk the stairs', 'Stair climbing is an efficient cardio exercise.'),
(7, 'Do burpees', 'Full-body exercise that''s highly effective.'),
(7, 'Practice balance exercises', 'Improve stability with single-leg stands.'),
(7, 'Go hiking', 'Nature + exercise = double benefit.'),
(7, 'Do lunges', 'Lunges target your legs and balance.'),
(7, 'Jump rope', 'Inexpensive, effective cardio exercise.'),
(7, 'Join a gym', 'Structured environment supports consistency.'),
(7, 'Try HIIT training', 'High-intensity interval training is time-efficient.'),
(7, 'Use a rowing machine', 'Rows work upper and lower body.'),
(7, 'Do sit-ups or crunches', 'Build abdominal strength.'),
(7, 'Try pilates', 'Pilates improves core strength and flexibility.'),
(7, 'Do wall sits', 'Hold a static position to build leg strength.'),
(7, 'Practice tai chi', 'Gentle martial art that improves balance.'),
(7, 'Use resistance bands', 'Effective for strength training anywhere.'),
(7, 'Do mountain climbers', 'Cardio and core work combined.'),
(7, 'Try kickboxing', 'Fun, intense workout that''s also stress-relieving.'),
(7, 'Go skateboarding', 'Fun exercise that engages balance.'),
(7, 'Do kettlebell swings', 'Explosive movement that builds strength.'),
(7, 'Try rollerblading', 'Fun cardio alternative to running.'),
(7, 'Use a jump bike', 'Indoor cycling that''s popular and effective.'),
(7, 'Do push-up variations', 'Try different grips and angles.'),
(7, 'Practice handstands', 'Build shoulder and core strength.'),
(7, 'Do calf raises', 'Strengthen your lower legs.'),
(7, 'Try water aerobics', 'Low-impact but effective exercise.'),
(7, 'Do lateral raises', 'Strengthen your shoulders.'),
(7, 'Participate in a team sport', 'Sports make exercise social and fun.'),
(7, 'Do tricep dips', 'Effective for arm strength.'),
(7, 'Try cross-training', 'Mix different types of exercise.'),
(7, 'Do high knees', 'Cardio and leg work.'),
(7, 'Use a treadmill', 'Walking or running in a controlled environment.'),
(7, 'Do glute bridges', 'Strengthen your glutes and core.'),
(7, 'Try trampoline exercise', 'Fun cardio that''s low-impact.'),
(7, 'Do shadow boxing', 'Cardio and stress relief combined.'),
(7, 'Walk at a brisk pace', 'Increase intensity while walking.'),
(7, 'Do ab wheel rollouts', 'Advanced core strengthening.'),
(7, 'Practice rock climbing', 'Fun, challenging full-body workout.');

-- Gratitude advice (50 records)
INSERT INTO public.advice (advice_type_id, title, content) VALUES
(8, 'Write three things you''re grateful for', 'Research shows gratitude journaling improves mood.'),
(8, 'Thank someone who has helped you', 'Express genuine appreciation to someone.'),
(8, 'Notice something beautiful around you', 'Pause to appreciate natural beauty.'),
(8, 'Appreciate your body', 'Be grateful for what your body can do.'),
(8, 'Think about a meal you enjoyed', 'Appreciate the nourishment and taste.'),
(8, 'Be grateful for your home', 'Recognize the shelter and safety you have.'),
(8, 'Appreciate people in your life', 'Think about who supports and loves you.'),
(8, 'Be grateful for your health', 'Appreciate your physical and mental well-being.'),
(8, 'Notice a moment of kindness', 'Someone was kind to you; acknowledge it.'),
(8, 'Appreciate a skill you have', 'Be grateful for an ability you''ve developed.'),
(8, 'Think about something you learned today', 'Growth and learning are gifts.'),
(8, 'Be grateful for your senses', 'Vision, hearing, taste, touch, smell—what gifts.'),
(8, 'Appreciate comfortable clothes', 'Notice the comfort you''re wearing.'),
(8, 'Be grateful for hot water', 'Access to hot water is a luxury many lack.'),
(8, 'Appreciate clean air', 'Grateful breathing is something we often overlook.'),
(8, 'Think about something that made you laugh', 'Laughter is a gift; appreciate it.'),
(8, 'Be grateful for your mind''s ability to think', 'Your consciousness is remarkable.'),
(8, 'Appreciate a meaningful relationship', 'Reflect on someone who matters to you.'),
(8, 'Be grateful for rest', 'The ability to rest and recover is valuable.'),
(8, 'Notice something your loved ones do for you', 'Small acts of care are often overlooked.'),
(8, 'Appreciate a favorite song', 'Music is a gift that enriches life.'),
(8, 'Be grateful for your job or work', 'Notice what you appreciate about what you do.'),
(8, 'Appreciate a moment of peace', 'Quiet moments are precious.'),
(8, 'Be grateful for technology', 'It connects us and helps us thrive.'),
(8, 'Notice something someone did well', 'Appreciate others'' efforts and abilities.'),
(8, 'Be grateful for nature', 'Trees, water, sky—natural beauty is everywhere.'),
(8, 'Appreciate a book or story', 'Stories transport us and teach us.'),
(8, 'Be grateful for your education', 'Knowledge is power; appreciate what you''ve learned.'),
(8, 'Appreciate safe transportation', 'The ability to travel safely is significant.'),
(8, 'Be grateful for cultural experiences', 'Arts, music, food—culture enriches life.'),
(8, 'Notice something that worked out well', 'Acknowledge when things go right.'),
(8, 'Be grateful for growth opportunities', 'Challenges that help you grow are gifts.'),
(8, 'Appreciate a meal', 'Think about the effort that went into your food.'),
(8, 'Be grateful for downtime', 'Time to relax and recharge is crucial.'),
(8, 'Appreciate a helpful tool or object', 'Objects that serve us are worth appreciating.'),
(8, 'Be grateful for your freedom', 'The ability to make choices is precious.'),
(8, 'Notice small beauties', 'A flower, sunrise, or smile are everyday miracles.'),
(8, 'Appreciate a conversation', 'Connection with others is valuable.'),
(8, 'Be grateful for moments of joy', 'Happiness deserves acknowledgment.'),
(8, 'Appreciate your creativity', 'Your ability to create is unique and valuable.'),
(8, 'Be grateful for your resilience', 'You''ve overcome challenges; that''s powerful.'),
(8, 'Notice supportive people around you', 'Community and support are crucial.'),
(8, 'Be grateful for second chances', 'The ability to try again is a gift.'),
(8, 'Appreciate simple pleasures', 'Coffee, a smile, a comfortable chair.'),
(8, 'Be grateful for your potential', 'You have the ability to grow and change.');

-- Problem Solving advice (50 records)
INSERT INTO public.advice (advice_type_id, title, content) VALUES
(9, 'Define the problem clearly', 'Write down what exactly you''re trying to solve.'),
(9, 'Break the problem into smaller parts', 'Large problems are easier when divided.'),
(9, 'Gather information', 'Research and understand the problem fully.'),
(9, 'List possible solutions', 'Brainstorm without judgment initially.'),
(9, 'Evaluate each option', 'Consider pros and cons of each solution.'),
(9, 'Ask for advice', 'Others'' perspectives can offer new insights.'),
(9, 'Take a break from the problem', 'Fresh perspective comes after stepping away.'),
(9, 'Use the "5 Whys" technique', 'Ask why five times to find root causes.'),
(9, 'Create a mind map', 'Visualize connections between aspects of the problem.'),
(9, 'Research similar problems', 'How have others solved similar issues?'),
(9, 'Test small solutions first', 'Try pilot versions before full commitment.'),
(9, 'Document what doesn''t work', 'Eliminating options helps find solutions.'),
(9, 'Set a decision deadline', 'Analysis paralysis is real; set a time limit.'),
(9, 'Consult an expert', 'Professional advice can accelerate solutions.'),
(9, 'Look for patterns', 'What similarities exist in the problem?'),
(9, 'Challenge your assumptions', 'Your assumptions might be wrong.'),
(9, 'Think of unconventional solutions', 'Creative thinking often leads to breakthroughs.'),
(9, 'Consider worst-case scenarios', 'Prepare for the worst; plan for the best.'),
(9, 'Use a decision matrix', 'Score options against important criteria.'),
(9, 'Talk it through out loud', 'Verbalizing helps organize thinking.'),
(9, 'Set a time limit for deciding', 'Avoid endless deliberation.'),
(9, 'Get feedback on your solution', 'Others may see flaws you missed.'),
(9, 'Implement the solution', 'Action beats perfect planning.'),
(9, 'Monitor the results', 'See if your solution works.'),
(9, 'Be willing to adjust', 'Solutions might need tweaking.'),
(9, 'Learn from the process', 'What will you do differently next time?'),
(9, 'Document the solution', 'Keep records for future reference.'),
(9, 'Teach others your solution', 'Explaining deepens understanding.'),
(9, 'Celebrate solving it', 'Acknowledge your problem-solving success.'),
(9, 'Use logic and data', 'Let facts guide your decisions.'),
(9, 'Consider multiple perspectives', 'How do different people view this?'),
(9, 'Try a cost-benefit analysis', 'Evaluate financial and time impacts.'),
(9, 'Ask clarifying questions', 'Deeper understanding prevents mistakes.'),
(9, 'Use process of elimination', 'Remove impossible options systematically.'),
(9, 'Think about long-term effects', 'Solutions have future consequences.'),
(9, 'Involve stakeholders', 'Get input from affected parties.'),
(9, 'Create an action plan', 'Turn solution into concrete steps.'),
(9, 'Set a timeline', 'When will each step happen?'),
(9, 'Identify resources needed', 'What do you need to implement?'),
(9, 'Plan for obstacles', 'What might go wrong?'),
(9, 'Create contingency plans', 'What if plan A doesn''t work?'),
(9, 'Track progress', 'Monitor your movement toward solving it.'),
(9, 'Adjust as needed', 'Problems often require course correction.'),
(9, 'Seek patterns in past solutions', 'Use what worked before.'),
(9, 'Stay calm', 'Panic clouds judgment and problem-solving.'),
(9, 'Trust your ability', 'You''ve solved problems before; you can again.');

-- Breathing Exercises advice (50 records)
INSERT INTO public.advice (advice_type_id, title, content) VALUES
(10, 'Try box breathing', 'Inhale 4, hold 4, exhale 4, hold 4. Repeat 5 times.'),
(10, 'Do belly breathing', 'Breathe deeply into your abdomen, not your chest.'),
(10, 'Practice 4-7-8 breathing', 'Inhale 4, hold 7, exhale 8. Very calming.'),
(10, 'Do alternate nostril breathing', 'Close one nostril while breathing; switch sides.'),
(10, 'Try pursed-lip breathing', 'Breathe in through nose, out slowly through pursed lips.'),
(10, 'Do slow, deep breathing', 'Simply slow your breathing down significantly.'),
(10, 'Try square breathing', 'Count equal breaths in, hold, out, hold.'),
(10, 'Practice coherent breathing', 'Breathe 5-6 times per minute for calm.'),
(10, 'Do diaphragmatic breathing', 'Engage your diaphragm, not your upper chest.'),
(10, 'Try lion''s breath', 'Inhale, then exhale forcefully with an open mouth.'),
(10, 'Do energizing breath', 'Short, quick breaths to increase energy.'),
(10, 'Practice yogic breathing', 'Ujjayi breath: slightly constricted breathing sound.'),
(10, 'Try straw breathing', 'Breathe in through nose, out slowly through a straw.'),
(10, 'Do humming bee breath', 'Make a humming sound on the exhale.'),
(10, 'Practice ocean breath', 'Create a wave-like sound with your breath.'),
(10, 'Try fire breath', 'Quick, forceful abdominal breathing.'),
(10, 'Do extended exhale breathing', 'Make exhales longer than inhales.'),
(10, 'Practice resonance breathing', 'Breathe at a pace that feels natural and calming.'),
(10, 'Try segmented breathing', 'Break breaths into small segments.'),
(10, 'Do nostril dominance balancing', 'Balance breathing between nostrils.'),
(10, 'Practice sigh breathing', 'Take a deep breath and sigh with relief.'),
(10, 'Try abdominal breathing', 'Expand belly as you inhale, contract as you exhale.'),
(10, 'Do lateral breathing', 'Focus on expanding your ribs sideways.'),
(10, 'Practice back breathing', 'Feel breath in your back body.'),
(10, 'Try counting breaths', 'Count each breath to focus your mind.'),
(10, 'Do synchronized breathing', 'Coordinate breathing with movement.'),
(10, 'Practice 3-part breathing', 'Abdomen, ribs, then chest on inhale.'),
(10, 'Try breath pauses', 'Pause briefly at the top of inhale and exhale.'),
(10, 'Do morning breath awareness', 'Start your day with conscious breathing.'),
(10, 'Practice transition breathing', 'Use breathing to transition between activities.'),
(10, 'Try calming count breathing', 'Inhale 1-2-3, exhale 1-2-3-4.'),
(10, 'Do energizing count breathing', 'Quick inhales and exhales to boost energy.'),
(10, 'Practice presence breathing', 'Use breath to return to the present moment.'),
(10, 'Try emotional release breathing', 'Use breath to release stored emotions.'),
(10, 'Do throat breathing', 'Create sound by slightly constricting your throat.'),
(10, 'Practice wind breathing', 'Fast, forceful breathing to energize.'),
(10, 'Try conscious relaxation breathing', 'Breathe while consciously relaxing muscles.'),
(10, 'Do focus breathing', 'Use breath as a focal point for meditation.'),
(10, 'Practice confidence breathing', 'Use breath to build self-assurance.'),
(10, 'Try anxiety-release breathing', 'Long exhales to release anxiety.'),
(10, 'Do power breathing', 'Strong inhales and exhales to build energy.'),
(10, 'Practice grounding breathing', 'Use breath to feel connected to the earth.'),
(10, 'Try stress-release sighing', 'Audible sighs with relief on exhale.'),
(10, 'Do awareness breathing', 'Notice the temperature and movement of breath.'),
(10, 'Practice rhythm breathing', 'Find a breathing rhythm that feels natural.'),
(10, 'Try gratitude breathing', 'Use breathing while thinking grateful thoughts.'),
(10, 'Do compassion breathing', 'Breathe while thinking kind thoughts for others.');